### ISSUE TITLE
مشکل نصب افزونه

### ISSUE THREAD

**Issue by SalmanAghaei** [gh-darvishani/magento2_zarinpay#1]
با سلام و خسته نباشد
من هنگام نصب افزونه بر روی مجنتو 2.2.3موقع اجرای دستور
php magnto setup:di:compile
با خطای
85% 41 secs 274.0 MiBErrors during compilation:
        Magento\Backend\Model\View\Layout\GeneratorPool
                Incompatible argument type: Required type: \Magento\Framework\View\Layout\Condition\ConditionFactory. Actual type: \Magento\Framework\App\Config\ScopeConfigInterface; File:
/home/bizanca/public_html/test/vendor/magento/module-backend/Model/View/Layout/GeneratorPool.php

Total Errors Count: 1

  [Magento\Framework\Validator\Exception]
  Error during compilation
مواجه میشم
میشه راهنمایی بفرماید

**Comment by gh-darvishani** [comment]
سلام 
این مشکل بعد از نصب ماژول درگاه زرین پال به وجود اومده ؟
شاید لازم باشه دسترسی های سرور رو بدید تا بررسی کنیم و اگه با این کار مشکلی ندارید اعلام امادگی بفرمایید
